name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  validate-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate HTML
        run: |
          npm install -g html-proofer
          htmlproofer ./ --only-4xx

  check-bundle-size:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check bundle size
        uses: simonplend/check-bundle-size-action@v1
        with:
          files: |
            **/*.js
            **/*.css

  accessibility:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run pa11y-ci
        run: |
          npm install -g pa11y-ci
          pa11y-ci --config pa11y-ci.json

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages

